apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-ui
  labels:
    app: axion-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axion-ui
  template:
    metadata:
      labels:
        app: axion-ui
    spec:
      containers:
        - name: axion-ui
          image: ghcr.io/contactanamika55/axion-ui:82df5f2
          ports:
            - containerPort: 80